version: "3.8"
services:
  client:
    container_name: react1
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: .
        target: /app

  client-test:
    container_name: test1
    command: ["npm", "run", "test"]
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: .
        target: /app
    stdin_open: true
    tty: true
