version: "3.8"
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./client
        target: /app

  client-test:
    container_name: client-test
    command: ["npm", "run", "test"]
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./client
        target: /app
    stdin_open: true
    tty: true
