version: "3.8"
services:
  client:
    container_name: react1
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: .
        target: /app
