version: "3.8"
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./client/src
        target: /app/client/src

  client-test:
    container_name: client-test
    command: ["npm", "run", "test"]
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./client
        target: /app/client/src
    stdin_open: true
    tty: true

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3001:80
    volumes:
      - type: bind
        source: ./api/src
        target: /app/api/src
